# Generated by Django 2.1.1 on 2018-10-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='city',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='dl_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='player_of_match',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='result',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='team1',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='team2',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='toss_decision',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='toss_winner',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='venue',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AddField(
            model_name='matches',
            name='win_by_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='win_by_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner',
            field=models.CharField(default='not set', max_length=50),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(default='not set', max_length=50),
        ),
    ]
