# Generated by Django 2.1.1 on 2018-10-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181002_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField(null=True)),
                ('batting_team', models.CharField(max_length=50, null=True)),
                ('bowling_team', models.CharField(max_length=50, null=True)),
                ('over', models.IntegerField(null=True)),
                ('ball', models.IntegerField(null=True)),
                ('batsman', models.CharField(max_length=50, null=True)),
                ('non_striker', models.CharField(max_length=50, null=True)),
                ('bowler', models.CharField(max_length=50, null=True)),
                ('is_super_over', models.IntegerField(null=True)),
                ('wide_runs', models.IntegerField(null=True)),
                ('bye_runs', models.IntegerField(null=True)),
                ('legbye_runs', models.IntegerField(null=True)),
                ('noball_runs', models.IntegerField(null=True)),
                ('penalty_runs', models.IntegerField(null=True)),
                ('batsman_runs', models.IntegerField(null=True)),
                ('extra_runs', models.IntegerField(null=True)),
                ('total_runs', models.IntegerField(null=True)),
                ('player_dismissed', models.CharField(max_length=50, null=True)),
                ('dismissal_kind', models.CharField(max_length=50, null=True)),
                ('fielder', models.CharField(max_length=50, null=True)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Matches')),
            ],
        ),
    ]
