# Generated by Django 2.1.1 on 2018-10-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_deliveries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='match_id',
        ),
    ]
