# Generated by Django 2.1.1 on 2018-10-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_deliveries_match_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='batsman',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='batsman_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='batting_team',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='bowler',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='bowling_team',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='bye_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='dismissal_kind',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='extra_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='fielder',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='inning',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='is_super_over',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='legbye_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='noball_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='non_striker',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='over',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='penalty_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='player_dismissed',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='total_runs',
        ),
        migrations.RemoveField(
            model_name='deliveries',
            name='wide_runs',
        ),
    ]
