# Generated by Django 2.1.1 on 2018-10-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20181002_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='city',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='date',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='dl_applied',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='player_of_match',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='result',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='season',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='toss_decision',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='toss_winner',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='umpire1',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='umpire2',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='umpire3',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='win_by_runs',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='win_by_wickets',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='winner',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='ball',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='batsman',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='batsman_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='batting_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='bowler',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='bowling_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='bye_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='extra_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='fielder',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='inning',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='is_super_over',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='legbye_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='noball_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='non_striker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='over',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='penalty_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='player_dismissed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='total_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='wide_runs',
            field=models.IntegerField(null=True),
        ),
    ]
