# Generated by Django 2.1.1 on 2018-10-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20181002_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='match_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Matches'),
        ),
    ]
