# Generated by Django 2.1.1 on 2018-10-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20181002_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='venue',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
